CREATE TABLE IF NOT EXISTS users (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login CHAR(32) NOT NULL,
	password CHAR(32) NOT NULL
	);

CREATE TABLE IF NOT EXISTS online_users (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login CHAR(32) NOT NULL,
	ptr BIGINT NOT NULL
	);
