#ifndef ERR_H
#define ERR_H

enum ERRORS {
	NO_ERROR,
	ERROR_UNKNOWN_LOGIN_OR_PASSWORD,
	ERROR_EXCEED_LOGIN_OR_PASSWORD_CHARACTER_COUNT,
	ERROR_LOGIN_EXISTS,
	ERROR_EXCEED_COUNT_SEARCH,
	ERROR_EXCEED_COUNT_FOR_WHAT,
	ERROR_EXCEED_COUNT_INTERESTS,
	ERROR_EXCEED_BIRTHDAY_DAY,
	ERROR_EXCEED_BIRTHDAY_MONTH,
	ERROR_CURRENT_USER_IS_NOT_ONLINE,
	ERROR_NOT_I_AM,
	ERROR_EXCEED_I_AM,
	ERROR_EXCEED_SEARCH,
	ERROR_LOGIN_OR_PASSWORD_IS_NULL,
	ERROR_EXCEED_MAX_SEARCH_PARAM,
	ERROR_NOT_CORRECT_MONTH_BIRTHDAY,
	ERROR_NOT_CORRECT_DAY_BIRTHDAY,
	ERROR_NOT_FOUND_FREE_INDEX,
	ERROR_UPLOAD_TO_UNAVAILABLE_FILE,
	ERROR_INDEX_UPLOAD_PHOTO_ALREADY_FREE,
	ERROR_EXCEED_UPLOAD_SIZE,
	ERROR_BUFFER_OVERFLOW,
	N_ERRORS
};


#endif
